project:
  type: website
  output-dir: docs
  #lib-dir: "libs"
  #output-dir: _site

website:
  title: "Data Science in Comparative Politics"
  site-url: "https://sebastianstier.com/ds_comp_pol25/"
  search: false
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: material.qmd
        text: Material
      - href: slides.qmd
        text: Slides
    # right:
    #   - text: ILIAS
    #     href: "https://ilias.uni-mannheim.de/ilias.php?baseClass=ilrepositorygui&ref_id=1527661"
  page-footer:
    left: "Sebastian Stier 2025"
    right: "Powered by [Quarto](https://quarto.org)"

format:
  html:
    theme: 
      - yeti
      - custom.scss
    css: styles.css
    toc: true
    
execute: 
  freeze: auto