---
title: Data Science in Comparative Politics
subtitle: "Teaching Presentation @ University of Hamburg, Summer semester 2025"
section-divs: false
toc: false
title-block-banner: "#58748F"
title-block-banner-color: "white"
format:
  html:
    link-external-icon: true
    link-external-newwindow: true
---

## Lecturer

### Sebastian Stier

Professor \@ University of Mannheim & Scientific Director Department Computational Social Science \@ GESIS

[{{< fa house size=1x >}}](https://sebastianstier.com)

## About the course

In this course, students learn about applications of data science in comparative politics. The course will be application oriented. Students will familiarize themselves with the main applications of data science methods and implement them in R. The range of applications will cover data management and preprocessing, data and results visualization, statistical data analysis, text as data methods and the validation of results. The hands-on application examples will cover questions from various research fields and different data types like country-level data or social media data. Equipped with this theoretical and methodological toolkit, students will develop their own data science research projects.

## Schedule

```{r, echo=FALSE, warning=FALSE, out.width="105%", message=FALSE}
library(openxlsx)
library(tidyverse)
library(gapminder)
library(plotly)
library(gt)
library(gtExtras)
read.xlsx("material/data/schedule.xlsx") %>%
    rename(`Required reading` = "Required.reading") %>%
    head(6) %>% 
    gt() %>%
    tab_header(md("**Seminar dates and topics**")) %>%
    #tab_header("**Seminar dates and topics**") %>%
    #fmt_markdown() %>% #columns = TRUE
    # cols_width(Date ~ px(400)#,
    #            #Topics ~ px(350)#,
    #            #`Required reading` ~ px(400)
    #            ) %>%
    cols_width(Date ~ pct(20),
               Topics ~ pct(30),
               `Required reading` ~ pct(50)
               ) %>%
    tab_options(data_row.padding = px(3)) %>%
    tab_options(heading.title.font.size = 14,
                column_labels.font.weight = "bold",
                table.font.size = 13.5) %>%
  fmt_markdown() %>% 
  cols_align(
    align = "left",
    columns = everything()
  )


```

## Software

-   [R](https://cran.rstudio.com)
-   A text editor, e.g. [RStudio](https://posit.co/download/rstudio-desktop)
-   [Quarto](https://quarto.org)
